apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: sureshkiran/stsdevops:v1
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
        - containerPort: 8080
